dataset_root: null

use_multiprocessing: True

tasks:
  initialize:
    task_name: "initialize"
    dataset_config_filename: "dataset_config.json"
    use_directory_index: False
    skip_dirs: []
    select_dirs: []

  groom_lungs:
    task_name: "groom_lungs"
    mesh_filenames: { lul: "left_lower", lll: "left_upper", rul: "right_upper", rml: "right_middle", rll: "right_lower" }
    params: { }

  logging:
    task_name: "logging"

run_tasks: []