defaults:
  - _self_
  - default_config: whole_lung
  - optional user_config: whole_lung
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  searchpath:
    - file://.
  output_subdir: null
  run:
    dir: .

initialize_user_config: False