defaults:
  - _self_
  - optional config: local_config
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  searchpath:
    - file://.
  output_subdir: null
  run:
    dir: .

config:
  dataset_root: null

  use_multiprocessing: True

  tasks:
    initialize:
      task_name: "initialize"
      dataset_config_filename: "dataset_config.json"
      use_directory_index: False
      skip_dirs: []
      select_dirs: []

    groom:
      task_name: "groom_lungs"
      mesh_filenames: { lul: "left_lower", lll: "left_upper", rul: "right_upper", rml: "right_middle", rll: "right_lower" }
      params: {}


    logging:
      task_name: "logging"

  run_tasks: []